-- VHDL Entity RISCV_lib.add4.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 15:03:32 05/09/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY add4 IS
   PORT( 
      pc_if        : IN     word;
      if_u_next_pc : OUT    word
   );

-- Declarations

END add4 ;

