-- VHDL Entity RISCV_lib.alu.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 18:51:12 06/13/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY alu IS
   PORT( 
      alu_mode_ex : IN     alu_mode_type;
      value_a     : IN     word;
      value_b     : IN     word;
      alu_out_ex  : OUT    word
   );

-- Declarations

END alu ;

