-- VHDL Entity RISCV_lib.big_to_little_endian.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 16:16:29 06/20/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY big_to_little_endian IS
   PORT( 
      store_data_2_big_end_dm    : IN     word;
      store_data_2_little_end_dm : OUT    word
   );

-- Declarations

END big_to_little_endian ;

