-- VHDL Entity RISCV_lib.clk_gen.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 15:03:10 05/09/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY clk_gen IS
   PORT( 
      clk   : OUT    std_logic;
      res_n : OUT    std_logic
   );

-- Declarations

END clk_gen ;

