-- VHDL Entity RISCV_lib.dc_reg.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 20:42:19 06/27/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY dc_reg IS
   PORT( 
      alu_mode_dc   : IN     alu_mode_type;
      clk           : IN     std_logic;
      fwd_sela_dc   : IN     std_logic_vector (1 DOWNTO 0);
      fwd_selb_dc   : IN     std_logic_vector (1 DOWNTO 0);
      fwd_selsd_dc  : IN     std_logic;
      imm_bta_dc    : IN     word;
      imm_to_alu_dc : IN     std_logic;
      mem_mode_dc   : IN     mem_mode_type;
      reg_A_dc      : IN     word;
      reg_B_dc      : IN     word;
      res_n         : IN     std_logic;
      target_reg_dc : IN     REG_ADDR;
      alu_mode_ex   : OUT    alu_mode_type;
      fwd_sela_ex   : OUT    std_logic_vector (1 DOWNTO 0);
      fwd_selb_ex   : OUT    std_logic_vector (1 DOWNTO 0);
      fwd_selsd_ex  : OUT    std_logic;
      imm_ex        : OUT    word;
      imm_to_alu_ex : OUT    std_logic;
      mem_mode_ex   : OUT    mem_mode_type;
      reg_B_ex_1    : OUT    word;
      target_reg_ex : OUT    REG_ADDR;
      value_a_1     : OUT    word
   );

-- Declarations

END dc_reg ;

