-- VHDL Entity RISCV_lib.dec.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 20:42:19 06/27/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY dec IS
   PORT( 
      instr_dc            : IN     word;
      mem_mode_ex         : IN     mem_mode_type;
      target_reg_ex       : IN     REG_ADDR;
      target_reg_me       : IN     reg_addr;
      alu_mode_dc         : OUT    alu_mode_type;
      fwd_sela_dc         : OUT    std_logic_vector (1 DOWNTO 0);
      fwd_selb_dc         : OUT    std_logic_vector (1 DOWNTO 0);
      fwd_selsd_dc        : OUT    std_logic;
      imm_dc              : OUT    word;
      imm_dec_control_mux : OUT    std_logic;
      imm_to_alu_dc       : OUT    std_logic;
      mem_mode_dc         : OUT    mem_mode_type;
      sela_dec            : OUT    reg_addr;
      selb_dec            : OUT    reg_addr;
      target_reg_dc       : OUT    REG_ADDR
   );

-- Declarations

END dec ;

