-- VHDL Entity RISCV_lib.dec_add_one.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 14:15:01 06/20/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY dec_add_one IS
   PORT( 
      imm_dc      : IN     word;
      pc_dec      : IN     word;
      dec_add2mux : OUT    word
   );

-- Declarations

END dec_add_one ;

