-- VHDL Entity RISCV_lib.dec_mux_imm.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 16:03:34 06/13/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY dec_mux_imm IS
   PORT( 
      dec_add2mux         : IN     word;
      imm_dc              : IN     word;
      imm_dec_control_mux : IN     std_logic;
      imm_bta_dc          : OUT    word
   );

-- Declarations

END dec_mux_imm ;

