-- VHDL Entity RISCV_lib.dm.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 19:10:34 06/20/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY dm IS
   PORT( 
      alu_out_me_b    : IN     word;
      clk             : IN     std_logic;
      mem_mode_me     : IN     mem_mode_type;
      res_n           : IN     std_logic;
      store_data_2_dm : IN     word;
      value_dm        : OUT    word
   );

-- Declarations

END dm ;

