-- VHDL Entity RISCV_lib.dm_mux.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 19:10:34 06/20/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY dm_mux IS
   PORT( 
      alu_out_me  : IN     word;
      mem_mode_me : IN     mem_mode_type;
      value_dm    : IN     word;
      me_out_me   : OUT    word
   );

-- Declarations

END dm_mux ;

