-- VHDL Entity RISCV_lib.dm_reg.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 18:49:54 06/13/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY dm_reg IS
   PORT( 
      clk           : IN     std_logic;
      me_out_me     : IN     word;
      res_n         : IN     std_logic;
      target_reg_me : IN     reg_addr;
      reg_addr_wb   : OUT    reg_addr;
      reg_value_wb  : OUT    word
   );

-- Declarations

END dm_reg ;

