-- VHDL Entity RISCV_lib.ex_reg.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 11:13:29 07/04/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY ex_reg IS
   PORT( 
      alu_out_ex    : IN     word;
      clk           : IN     std_logic;
      fwd_selsd_ex  : IN     std_logic;
      mem_mode_ex   : IN     mem_mode_type;
      reg_B_ex      : IN     word;
      res_n         : IN     std_logic;
      target_reg_ex : IN     REG_ADDR;
      alu_out_me    : OUT    word;
      fwd_selsd_me  : OUT    std_logic;
      mem_mode_me   : OUT    mem_mode_type;
      store_data_dm : OUT    word;
      target_reg_me : OUT    reg_addr
   );

-- Declarations

END ex_reg ;

