-- VHDL Entity RISCV_lib.im.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 17:44:52 05/16/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY im IS
   PORT( 
      pc_if      : IN     word;
      res_n      : IN     std_logic;
      if_u_instr : OUT    word
   );

-- Declarations

END im ;

