-- VHDL Entity RISCV_lib.little_to_big_endian.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 16:18:38 06/20/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY little_to_big_endian IS
   PORT( 
      value_little_end_dm : IN     word;
      value_big_end_dm    : OUT    word
   );

-- Declarations

END little_to_big_endian ;

