-- VHDL Entity RISCV_lib.mp_if.generatedInstance
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 11:13:29 07/04/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY mp_if IS
END mp_if ;

