-- VHDL Entity RISCV_lib.pc_reg.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 15:36:35 06/13/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY pc_reg IS
   PORT( 
      clk          : IN     std_logic;
      if_u_next_pc : IN     word;
      res_n        : IN     std_logic;
      pc_if        : OUT    word
   );

-- Declarations

END pc_reg ;

