-- VHDL Entity RISCV_lib.peripherie_01.generatedInstance
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 15:24:03 05/09/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY peripherie_01 IS
END peripherie_01 ;

