-- VHDL Entity RISCV_lib.proofer.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 18:04:21 06/20/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;

ENTITY proofer IS
   PORT( 
      alu_out_me   : IN     word;
      mem_mode_me  : IN     mem_mode_type;
      alu_out_me_b : OUT    word
   );

-- Declarations

END proofer ;

