-- VHDL Entity RISCV_lib.riscv.interface
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 15:03:10 05/09/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY riscv IS
   PORT( 
      clk   : IN     std_logic;
      res_n : IN     std_logic
   );

-- Declarations

END riscv ;

