--
-- VHDL Architecture RISCV_lib.riscv.struct
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 15:23:19 05/09/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
LIBRARY RISCV_lib;
USE RISCV_lib.opcode_word.ALL;


ARCHITECTURE struct OF riscv IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL if_u_instr   : word;
   SIGNAL if_u_next_pc : word;
   SIGNAL pc_if        : word;


   -- Component Declarations
   COMPONENT add4
   PORT (
      pc_if        : IN     word ;
      if_u_next_pc : OUT    word 
   );
   END COMPONENT;
   COMPONENT alu
   END COMPONENT;
   COMPONENT bpu
   END COMPONENT;
   COMPONENT dc_reg
   END COMPONENT;
   COMPONENT dec
   END COMPONENT;
   COMPONENT dm
   END COMPONENT;
   COMPONENT dm_reg
   END COMPONENT;
   COMPONENT ex_reg
   END COMPONENT;
   COMPONENT if_reg
   PORT (
      clk   : IN     std_logic;
      res_n : IN     std_logic
   );
   END COMPONENT;
   COMPONENT im
   PORT (
      pc_if      : IN     word ;
      if_u_instr : OUT    word 
   );
   END COMPONENT;
   COMPONENT mp_if
   END COMPONENT;
   COMPONENT pc_reg
   PORT (
      clk          : IN     std_logic ;
      if_u_next_pc : IN     word ;
      res_n        : IN     std_logic ;
      pc_if        : OUT    word 
   );
   END COMPONENT;
   COMPONENT rf
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : add4 USE ENTITY RISCV_lib.add4;
   FOR ALL : alu USE ENTITY RISCV_lib.alu;
   FOR ALL : bpu USE ENTITY RISCV_lib.bpu;
   FOR ALL : dc_reg USE ENTITY RISCV_lib.dc_reg;
   FOR ALL : dec USE ENTITY RISCV_lib.dec;
   FOR ALL : dm USE ENTITY RISCV_lib.dm;
   FOR ALL : dm_reg USE ENTITY RISCV_lib.dm_reg;
   FOR ALL : ex_reg USE ENTITY RISCV_lib.ex_reg;
   FOR ALL : if_reg USE ENTITY RISCV_lib.if_reg;
   FOR ALL : im USE ENTITY RISCV_lib.im;
   FOR ALL : mp_if USE ENTITY RISCV_lib.mp_if;
   FOR ALL : pc_reg USE ENTITY RISCV_lib.pc_reg;
   FOR ALL : rf USE ENTITY RISCV_lib.rf;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   add4_one : add4
      PORT MAP (
         pc_if        => pc_if,
         if_u_next_pc => if_u_next_pc
      );
   U_3 : alu;
   U_4 : bpu;
   U_9 : dc_reg;
   U_1 : dec;
   U_5 : dm;
   U_11 : dm_reg;
   U_10 : ex_reg;
   U_8 : if_reg
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );
   im_one : im
      PORT MAP (
         pc_if      => pc_if,
         if_u_instr => if_u_instr
      );
   U_7 : mp_if;
   pc_reg_one : pc_reg
      PORT MAP (
         clk          => clk,
         if_u_next_pc => if_u_next_pc,
         res_n        => res_n,
         pc_if        => pc_if
      );
   U_2 : rf;

END struct;
