--
-- VHDL Architecture RISCV_lib.soc_tb.struct
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 15:03:10 05/09/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

LIBRARY RISCV_lib;

ARCHITECTURE struct OF soc_tb IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk   : std_logic;
   SIGNAL res_n : std_logic;


   -- Component Declarations
   COMPONENT SOC
   PORT (
      clk   : IN     std_logic ;
      res_n : IN     std_logic 
   );
   END COMPONENT;
   COMPONENT clk_gen
   PORT (
      clk   : OUT    std_logic ;
      res_n : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : SOC USE ENTITY RISCV_lib.SOC;
   FOR ALL : clk_gen USE ENTITY RISCV_lib.clk_gen;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   i_soc : SOC
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );
   I_clock_gen : clk_gen
      PORT MAP (
         clk   => clk,
         res_n => res_n
      );

END struct;
