-- VHDL Entity RISCV_lib.soc_tb.symbol
--
-- Created:
--          by - flxpuchr.meyer (pc032)
--          at - 16:20:48 05/02/23
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2022.3 Built on 14 Jul 2022 at 13:56:12
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY soc_tb IS
-- Declarations

END soc_tb ;

